CONFIG_GPIO=y

# Habilita a API de ADC do Zephyr e o driver kinetis-adc16 da K64F
CONFIG_ADC=y

# Habilita a função printk()
CONFIG_SERIAL=y
# Habilita o suporte a números de ponto flutuante na função printk
CONFIG_NEWLIB_LIBC=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Habilita o subsistema de Logging do Zephyr
CONFIG_LOG=y
# Crucial: Processa os logs em background sem bloquear as threads de tempo real
CONFIG_LOG_MODE_DEFERRED=y
# Tamanho do buffer interno de log (em bytes)
CONFIG_LOG_BUFFER_SIZE=4096
